### ISSUE TITLE
Possible French AZERTY keyboard issue

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#38]
User on Windows 7, Python 3.4, running PyAutoGUI 0.9.30 and a French "AZERTY" keyboard reported being unable to simulate pressing : 

Running the unit tests, they got these results:

http://pastebin.com/gkHjUFRY

D:\Dropbox\Software\Python>test
......
a
ba
.Hello world§
Faxyz
abxc
c
xabcz
.Hello world§
F
# ......
## FAIL: test_typewrite (**main**.TestKeyboard)

Traceback (most recent call last):
  File "D:\Dropbox\Software\Python\test.py", line 394, in test_typewrite
    self.assertEqual(response, 'Hello world!')
AssertionError: 'Hello world§' != 'Hello world!'
- Hello world§
  ?            ^
- Hello world!
  ?            ^
# 
## FAIL: test_typewrite_slow (**main**.TestKeyboard)

Traceback (most recent call last):
  File "D:\Dropbox\Software\Python\test.py", line 426, in test_typewrite_slow
    self.assertEqual(response, 'Hello world!')
AssertionError: 'Hello world§' != 'Hello world!'
- Hello world§
  ?            ^
- Hello world!
  ?            ^

---

Ran 16 tests in 33.566s

FAILED (failures=2)

D:\Dropbox\Software\Python>

**Comment by Ousret** [comment]
Should be fixed with https://github.com/asweigart/pyautogui/pull/55

**Comment by asweigart** [comment]
Folding this into issue #137

**Comment by josephernest** [comment]
As of today (0.9.48), this is not solved on Win7 x64, Python 3.6, French keyboard layout.  
I still have: `Hello world§`

Any idea for a temporary fix?

Thanks in advance @asweigart!

**Comment by dezechristophe** [comment]
Hello,
I have the same issue PyAutoGUI   0.9.50
! always give §
any workaround ?
thanks
@josephernest

**Comment by TheBdouilleur** [comment]
Hello, same as @josephernest and @dezechristophe, 
it doesn't work either for other keys:
: gives /
/ gives :
@ gives à
à gives nothing (or space maybe ?)
and so on. Seems like everything is inversed (ie. Shift, AltGr ...)

**Comment by MUHAMMADSHAHSAWAR** [comment]
I have issue that when i write "/" with typewriter() in pyautogui it write ? in output of function.
